name: Java CI

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B verify "-Dspring.profiles.active=ci"
      - name: Build and test
        run: mvn -B verify "-Dspring.profiles.active=ci" pitest:mutationCoverage
      - name: Save repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.REPOSITORY_NAME }}-reports
          path: |
            target/site/jacoco/
            target/pit-reports/
